const appConstant={
    RECEIVED_SOLUTION:'RECEIVED_SOLUTION',
    RECEIVED_CONTRACT:'RECEIVED_CONTRACT',
    RECEIVED_REQUEST_PAY:'RECEIVED_REQUEST_PAY',
    RECEIVED_CONTRACT_ACCEPT:'RECEIVED_CONTRACT_ACCEPT',
    RECEIVED_CONTRACT_REJECT:'RECEIVED_CONTRACT_REJECT'
}

export default appConstant